#pragma once

namespace IE
{
	using MouseCode = uint16_t;

	enum : MouseCode
	{
		/* Mouse codes from glfw3.h */
		IE_MOUSE_BUTTON_1 = 0,
		IE_MOUSE_BUTTON_2 = 1,
		IE_MOUSE_BUTTON_3 = 2,
		IE_MOUSE_BUTTON_4 = 3,
		IE_MOUSE_BUTTON_5 = 4,
		IE_MOUSE_BUTTON_6 = 5,
		IE_MOUSE_BUTTON_7 = 6,
		IE_MOUSE_BUTTON_8 = 7,
		IE_MOUSE_BUTTON_LAST = IE_MOUSE_BUTTON_8,
		IE_MOUSE_BUTTON_LEFT = IE_MOUSE_BUTTON_1,
		IE_MOUSE_BUTTON_RIGHT = IE_MOUSE_BUTTON_2,
		IE_MOUSE_BUTTON_MIDDLE = IE_MOUSE_BUTTON_3
	};
}